# Create a Kafka user with SCRAM-SHA-512 authentication (no authorization)
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-kafka-user
  namespace: data-streaming
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512

---
# Create an admin user with full permissions
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-admin
  namespace: data-streaming
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512

---
# Example topic
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  namespace: data-streaming
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: 604800000  # 7 days
    segment.bytes: 1073741824
    compression.type: producer
    min.insync.replicas: 2

---
# Example topic with different settings
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: high-throughput-topic
  namespace: data-streaming
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 12
  replicas: 3
  config:
    retention.ms: 86400000  # 1 day
    segment.bytes: 536870912
    compression.type: lz4
    min.insync.replicas: 2